#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Cursor mouse fix.
# xsetroot -cursor_name left_ptr &

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc rule -a konsole state=floating

bspc config focused_border_color "#444444"
bspc config normal_border_color "#000000"
bspc config top_padding 1
bspc config bottom_padding 29
bspc config font "FiraCode Nerd Font Mono:size=7:style=Regular"

polybar &
